language: php

sudo: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

before_script:
  - composer install --no-interaction --prefer-source
  - composer global require "phpunit/phpunit=4.1.*"
  - export PATH=./vendor/bin:$PATH

script:
  - phpunit --stderr --coverage-clover build/logs/clover.xml --configuration phpunit.xml.dist test/
