language: php

sudo: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - make install

script:
  - make test-all-coverage
